# Generated by Django 2.2.1 on 2019-05-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='votes',
        ),
    ]
